id: I3BC3F0FE
ocr_import_info:
  timestamp: '2023-05-30T06:57:54.695030+00:00'
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.8
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-05-30 07:45:23.869744+00:00
last_modified: 2023-05-30 07:45:23.869751+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23911
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23911
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞི་བྱེད་སྔ་བར་ཕྱི་གསུམ་གྱི་སྐོར།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9654360442678908
  ocr_word_median_confidence_index: 0.9997795
bases:
  I1KG1695:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1695
      total_pages: 492
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG1695.txt
    statistics:
      ocr_word_median_confidence_index: 0.9998746249999999
      ocr_word_mean_confidence_index: 0.9715729454869823
  I1KG1696:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1696
      total_pages: 506
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG1696.txt
    statistics:
      ocr_word_median_confidence_index: 0.9995341
      ocr_word_mean_confidence_index: 0.9595591349421421
  I1KG1697:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1697
      total_pages: 442
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG1697.txt
    statistics:
      ocr_word_median_confidence_index: 0.99992794
      ocr_word_mean_confidence_index: 0.9657218907360978
  I1KG1694:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1694
      total_pages: 480
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1694.txt
    statistics:
      ocr_word_median_confidence_index: 0.9996385
      ocr_word_mean_confidence_index: 0.9685708243329597
  I1KG1698:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1698
      total_pages: 538
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG1698.txt
    statistics:
      ocr_word_median_confidence_index: 0.9997499
      ocr_word_mean_confidence_index: 0.9629506453085562
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
